CREATE TABLE `mestrado`.`KGNODE` (
  `id` INT NOT NULL,
  `label` VARCHAR(400) NULL,
  `uri` VARCHAR(400) NULL,
  `directHits` INT NULL,
  `indirectHitsType` INT NULL,
  `indirectHitsSubclassOf` INT NULL,
  PRIMARY KEY (`id`));
  
ALTER TABLE `mestrado`.`KGNODE` 
CHANGE COLUMN `LABEL` `LABEL` VARCHAR(400) NOT NULL ,
CHANGE COLUMN `URI` `URI` VARCHAR(400) NOT NULL ,
CHANGE COLUMN `DIRECTHITS` `DIRECTHITS` INT(11) NOT NULL ,
CHANGE COLUMN `INDIRECTHITSTYPE` `INDIRECTHITSTYPE` INT(11) NOT NULL ,
CHANGE COLUMN `INDIRECTHITSSUBCLASSOF` `INDIRECTHITSSUBCLASSOF` INT(11) NOT NULL ,
ADD COLUMN `TYPE` VARCHAR(45) NOT NULL COMMENT 'INSTANCE, CLASS' AFTER `INDIRECTHITSSUBCLASSOF`,
ADD UNIQUE INDEX `LABEL_UNIQUE` (`LABEL` ASC),
ADD UNIQUE INDEX `URI_UNIQUE` (`URI` ASC);

ALTER TABLE `mestrado`.`KGNODE` 
CHANGE COLUMN `DIRECTHITS` `DIRECTHITS` INT(11) UNSIGNED NOT NULL ,
CHANGE COLUMN `INDIRECTHITSTYPE` `INDIRECTHITSTYPE` INT(11) UNSIGNED NOT NULL ,
CHANGE COLUMN `INDIRECTHITSSUBCLASSOF` `INDIRECTHITSSUBCLASSOF` INT(11) UNSIGNED NOT NULL ;

  
ALTER TABLE `mestrado`.`KGNODE` 
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

CREATE TABLE `mestrado`.`KGNODE_SUBCLASS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDNODE` INT NOT NULL,
  `IDSUBCLASS` INT NOT NULL,
  PRIMARY KEY (`ID`));
  
  CREATE TABLE `mestrado`.`KGNODE_TYPE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDNODE` INT NOT NULL,
  `IDTYPE` INT NOT NULL,
  PRIMARY KEY (`ID`));

  CREATE TABLE `mestrado`.`BRIDGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDNODE` INT NOT NULL,
  `HIGH_LEVEL_CLASS` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`));
  ALTER TABLE `mestrado`.`BRIDGE` 
ADD COLUMN `TYPE` VARCHAR(45) NOT NULL COMMENT 'KEY, NEW, INCONSISTENT' AFTER `HIGH_LEVEL_CLASS`;

CREATE TABLE `mestrado`.`HIERARCHY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDROOT` INT NOT NULL,
  `IDNODE` INT NOT NULL,
  `LEVEL` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC));
  
ALTER TABLE `mestrado`.`KGNODE_SUBCLASS` 
CHANGE COLUMN `IDSUBCLASS` `IDSUPERCLASS` INT(11) NOT NULL , RENAME TO  `mestrado`.`KGNODE_SUPERCLASS` ;

ALTER TABLE `mestrado`.`BRIDGE` 
CHANGE COLUMN `IDNODE` `IDNODE` INT(11) UNSIGNED NOT NULL ;

CREATE TABLE `mestrado`.`Tweet` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `text` VARCHAR(280) NOT NULL,
  `creationDate` DATETIME NULL,
  `isRetweet` TINYINT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `mestrado`.`KGNODE_TWEET` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTweet` INT NOT NULL,
  `idNode` INT NOT NULL,
  PRIMARY KEY (`id`));

