CREATE TABLE BRIDGE_BKP AS SELECT * FROM BRIDGE;
CREATE TABLE KGNODE_BKP AS SELECT * FROM KGNODE;
CREATE TABLE KGNODE_SUPERCLASS_BKP AS SELECT * FROM KGNODE_SUPERCLASS;
CREATE TABLE KGNODE_TWEET_BKP AS SELECT * FROM KGNODE_TWEET;
CREATE TABLE KGNODE_TYPE_BKP AS SELECT * FROM KGNODE_TYPE;
CREATE TABLE SUPERCLASSES_PATH_BKP AS SELECT * FROM SUPERCLASSES_PATH;
CREATE TABLE TWEET_BKP AS SELECT * FROM TWEET;